module.exports = {
  FB_PAGE_TOKEN: process.env.FB_PAGE_TOKEN,
  FB_VERIFY_TOKEN: process.env.FB_VERIFY_TOKEN,
  API_AI_CLIENT_ACCESS_TOKEN: process.env.API_AI_CLIENT_ACCESS_TOKEN,
  FB_APP_SECRET: process.env.FB_APP_SECRET,
};